version: 2
jobs:
  code_quality:
    docker:
      - image: cimg/python:3.9.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-dependencies-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
              python -m venv env
              . env/bin/activate
              pip install -r requirements-dev.txt          
      - run:
          name: Run black
          command: |
            source env/bin/activate
            black trade_remedies_client --check
      - run:
          name: flake8
          command: |
            source env/bin/activate
            echo "this is where we run flake8"
            # flake8 --count
      - save_cache:
          paths:
            - env
          key: pip-dependencies-{{ checksum "requirements-dev.txt" }}
  
workflows:
  version: 2
  run_tests:
    jobs:
      - code_quality
